mfo/home/views.py
# mfo/home/views.py

import flask
import flask_security
from sqlalchemy import select
from flask_security.utils import verify_and_update_password

from mfo.database.base import db
import mfo.database.users as users
from mfo.database.models import Profile
from mfo.database.users import Role, User
from mfo.account.forms.edit_profile import ProfileEdit
import mfo.database.utilities
from mfo.database.models import Festival, Season
from mfo.home.forms import ExtendedLoginForm
from mfo.home.utilities import get_identity_attributes

bp = flask.Blueprint(
    'home',
    __name__,
    static_folder='static',
    template_folder='templates',
    static_url_path='/home/static',
    url_prefix='/'
    )


@bp.route('/')
def index():
    if '_flashes' in flask.session:
        flask.session['_flashes'].clear()

    if flask_security.current_user and flask_security.current_user.is_authenticated:
        festival = mfo.database.utilities.get_current_festival()

        if festival is None:
            flask.flash('No active festival', 'danger')
            return flask.redirect(flask.url_for('home.custom_login_get'))

        festival_users = [ufr.user for ufr in festival.roles_users]
        if flask_security.current_user not in festival_users:
            flask.flash('User not registered with festival', 'danger')
            return flask.redirect(flask.url_for('home.custom_login_get'))

        user_role_names = flask_security.current_user.role_names

        if 'Admin' in user_role_names:
            return flask.redirect(flask.url_for('admin.dashboard'))
        else:
            return flask.redirect(flask.url_for('home.dashboard'))

    return flask.render_template('/home/index.html')


@bp.get ('/dashboard')
@flask_security.auth_required()
def dashboard():
    return flask.render_template('/home/dashboard.html')


@bp.get('/new_user')
@flask_security.auth_required()
def new_user():
    role_name = "Participant"
    user = flask_security.current_user
    users.user_datastore.add_role_to_user(user, role_name)
    stmt = select(Role).where(Role.name == role_name)
    role = db.session.execute(stmt).scalars().first()

    primary_profile = Profile()
    primary_profile.email = user.email
    user, primary_profile = mfo.database.utilities.set_primary_profile(user, primary_profile)
    for role in user.roles:
        primary_profile.roles.append(role)

    primary_profile.users.append(user)

    db.session.add(primary_profile)
    db.session.commit()

    form = ProfileEdit(obj=primary_profile)

    return flask.render_template('/account/edit_profile.html', form=form)

@bp.get('/clogin')
def custom_login_get():
    form = ExtendedLoginForm()

    identity_attributes = get_identity_attributes()
    # if festival_nickname:
    #     stmt = select(Festival).where(Festival.nickname.ilike(festival_nickname))
    #     festival = db.session.execute(stmt).scalars().first()
    #     if festival:
    #         form.festival.data = festival.name
    #     else:
    #         flask.flash('Invalid Festival', 'danger')

    return flask.render_template(
        'security/custom_login_user.html', 
        identity_attributes=identity_attributes, 
        login_user_form=form
    )

@bp.post('/clogin')
def custom_login_post():
    form = ExtendedLoginForm()
    identity_attributes = get_identity_attributes()

    if form.validate():
        stmt = select(User).where(User.email == form.email.data)
        user = db.session.execute(stmt).scalars().first()

        if not user:
            flask.flash('Invalid email or password', 'error')
            return flask.render_template(
                'security/custom_login_user.html', 
                identity_attributes=identity_attributes,
                login_user_form=form
            )
        
        # Check if the user is associated with the selected festival
        festival_name = form.festival.data
        stmt = select(Festival).where(Festival.name == festival_name)
        festival = db.session.execute(stmt).scalars().one_or_none()

        if not festival:
            flask.flash('Invalid Festival', 'error')
            return flask.render_template(
                'security/custom_login_user.html', 
                identity_attributes=identity_attributes,
                login_user_form=form
            )

        user_festivals = [ufr.festival.name for ufr in user.roles_festivals]
        print(user_festivals)
        if festival.name not in user_festivals:
            flask.flash(f'User is not associated with {festival.name}', 'error')
            return flask.render_template(
                'security/custom_login_user.html', 
                identity_attributes=identity_attributes,
                login_user_form=form
            )

        success = flask_security.login_user(user, authn_via=["password"], remember=form.remember.data)
        print(f"****  {success}  ****************************************")
        if success:
            flask.session['current_festival'] = festival.id  # Store festival ID in session for future use
            # print(f"User: {flask_security.current_user.email}")
            # print(festival_name)
            # print(f"Festival: {flask.session['festival_id']}")
            return flask.redirect(flask.url_for('home.index'))
        else:
            flask.flash('Invalid email or password', 'error')
            return flask.render_template(
                'security/custom_login_user.html', 
                identity_attributes=identity_attributes,
                login_user_form=form
            )
    else:
        flask.flash('Invalid email or password validation', 'error')
        return flask.render_template(
                'security/custom_login_user.html', 
                identity_attributes=identity_attributes,
                login_user_form=form
            )

        
        # if user and verify_and_update_password(form.password.data, user):
        #     # Check if the user has access to the specified Festival and Season
        #     stmt = select(Festival).where(Festival.name == form.festival.data)
        #     festival = db.session.execute(stmt).scalars().first()
            
        #     if festival:
        #         stmt = select(Season).where(
        #             Season.primary == True, 
        #             Season.festival_id == festival.id
        #             )
        #         season = db.session.execute(stmt).scalars().first()
        #         print(f'Season: {season.name}')
                
        #         if season and user_has_access(user, festival, season):
        #             flask_security.login_user(user, remember=form.remember.data)
        #             return flask.redirect(flask.url_for('home.index'))
        #         else:
        #             flask.flash('No active season', 'error')
        #     else:
        #         flask.flash('Invalid Festival', 'error')
        #         return flask.render_template('security/login_user.html', login_user_form=form)
        # else:
        #     flask.flash('Invalid email or password', 'error')
        #     return flask.render_template('security/login_user.html', login_user_form=form)
    
def user_has_access(user, festival, season):
    # Implement your logic to check if the user has access to the festival 
    return True  # Replace with actual access check logic

mfo/templates/security/change_password.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors, render_form_errors %}

{% block content %}
<div class="row pt-4 pb-4">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8">
    {# {% include "security/_messages.html" %} #}
    <h1>{{ _fsdomain('Change password') }}</h1>
    <form action="{{ url_for_security('change_password') }}" method="post" name="change_password_form">
      {{ change_password_form.hidden_tag() }}
      {{ render_form_errors(change_password_form) }}
      {% if active_password %}
        {{ render_field_with_errors(change_password_form.password, class_="form-control mb-2") }}
      {% else %}
        <h3>{{ _fsdomain('You do not currently have a password - this will add one.') }}</h3>
      {% endif %}
      {{ render_field_with_errors(change_password_form.new_password, class_="form-control mb-2") }}
      {{ render_field_with_errors(change_password_form.new_password_confirm, class_="form-control mb-3") }}
      {{ render_field_errors(change_password_form.csrf_token) }}
      {{ render_field(change_password_form.submit, class_="btn btn-primary mb-2") }}
    </form>
  </div>
  <div class="col-sm-2">
  </div>
</div>
{% endblock content %}

mfo/templates/security/custom_login_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors, render_form_errors, prop_next %}

{% block content %}

{% include "flash.html" %}

<div class="row pt-4 pb-4">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        {# {% include "security/_messages.html" %} #}
        <h1 class="legend">{{ _fsdomain('Login') }}</h1>

        <p>Chices: {{login_user_form.festival.choices}}</p>
        <form action="{{ url_for('home.custom_login_post') }}{{ prop_next() }}" method="post" name="login_user_form">
            {{ login_user_form.hidden_tag() }}
            {{ render_form_errors(login_user_form) }}
            {% if "email" in identity_attributes %}
                {{ render_field_with_errors(login_user_form.email, class_="form-control mb-2") }}
            {% endif %}
            {% if login_user_form.username and "username" in identity_attributes %}
              {% if "email" in identity_attributes %}<h3>{{ _fsdomain("or") }}</h3>{% endif %}
              {{ render_field_with_errors(login_user_form.username, class_="form-control mb-2") }}
            {% endif %}
            {{ render_field_with_errors(login_user_form.password, class_="form-control mb-2") }}

            {{ render_field_with_errors(login_user_form.festival, class_="form-control mb-2") }}
            
            {{ render_field_with_errors(login_user_form.remember, class_="form-check-input mb-3 ms-2") }}
            {{ render_field_errors(login_user_form.csrf_token) }}
            {{ render_field(login_user_form.submit, class_="btn btn-primary mb-2") }}
        </form>
        {% if security.webauthn %}
            <hr class="fs-gap">
            <h2>{{ _fsdomain("Use WebAuthn to Sign In") }}</h2>
            <div>
                <form method="get" id="wan_signin_form" name="wan_signin_form">
                    <input id="wan_signin" name="wan_signin" type="submit" value="{{ _fsdomain('Sign in with WebAuthn') }}" formaction="{{ url_for_security('wan_signin') }}{{ prop_next() }}">
                </form>
            </div>
        {% endif %}
        {% if security.oauthglue %}
            <hr class="fs-gap">
            <h2>{{ _fsdomain("Use Social Oauth to Sign In") }}</h2>
            {% for provider in security.oauthglue.provider_names %}
              
                <form method="post" id="{{ provider }}_form" name="{{ provider }}_form">
                    <input id="{{ provider }}" name="{{ provider }}" type="submit" value="{{ _fsdomain('Sign in with ')~provider }}" formaction="{{ url_for_security('oauthstart', name=provider) }}{{ prop_next() }}">
                    {% if csrf_token is defined %}
                        <input id="{{ provider }}_csrf_token" name="{{ provider }}_csrf_token" type="hidden" value="{{ csrf_token() }}">
                    {% endif %}
                </form>
              </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="col-sm-2">
    </div>
</div>


{% endblock content %}

mfo/templates/security/login_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors, render_form_errors, prop_next %}

{% block content %}

{% include "flash.html" %}

<div class="row pt-4 pb-4">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        404
    </div>
    <div class="col-sm-2">
    </div>
</div>


{% endblock content %}

mfo/templates/security/login_user_nn.html
{% extends "shared_layout.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors, render_form_errors, prop_next %}

{% block main_content %}
  {% include "security/_messages.html" %}
  <h1>CUSTOM</h1>
  <h1>{{ _fsdomain('Login') }}</h1>
  <form action="{{ url_for_security('login') }}{{ prop_next() }}" method="post" name="login_user_form">
    {{ login_user_form.hidden_tag() }}
    {{ render_form_errors(login_user_form) }}
    {% if "email" in identity_attributes %}{{ render_field_with_errors(login_user_form.email) }}{% endif %}
    {% if login_user_form.username and "username" in identity_attributes %}
      {% if "email" in identity_attributes %}<h3>{{ _fsdomain("or") }}</h3>{% endif %}
      {{ render_field_with_errors(login_user_form.username) }}
    {% endif %}
    <div class="fs-gap">{{ render_field_with_errors(login_user_form.password) }}</div>
    {{ render_field_with_errors(login_user_form.remember) }}
    {{ render_field_errors(login_user_form.csrf_token) }}
    {{ render_field(login_user_form.submit) }}
  </form>
  {% if security.webauthn %}
    <hr class="fs-gap">
    <h2>{{ _fsdomain("Use WebAuthn to Sign In") }}</h2>
    <div>
      <form method="get" id="wan_signin_form" name="wan_signin_form">
        <input id="wan_signin" name="wan_signin" type="submit" value="{{ _fsdomain('Sign in with WebAuthn') }}" formaction="{{ url_for_security('wan_signin') }}{{ prop_next() }}">
      </form>
    </div>
  {% endif %}
  {% if security.oauthglue %}
    <hr class="fs-gap">
    <h2>{{ _fsdomain("Use Social Oauth to Sign In") }}</h2>
    {% for provider in security.oauthglue.provider_names %}
      <div class="fs-gap">
        <form method="post" id="{{ provider }}_form" name="{{ provider }}_form">
          <input id="{{ provider }}" name="{{ provider }}" type="submit" value="{{ _fsdomain('Sign in with ')~provider }}" formaction="{{ url_for_security('oauthstart', name=provider) }}{{ prop_next() }}">
          {% if csrf_token is defined %}
            <input id="{{ provider }}_csrf_token" name="{{ provider }}_csrf_token" type="hidden" value="{{ csrf_token() }}">
          {% endif %}
        </form>
      </div>
    {% endfor %}
  {% endif %}
  {% include "security/_menu.html" %}
{% endblock main_content %}

mfo/templates/security/register_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_form_errors, render_field_errors %}

{% block content %}
<div class="row pt-4 pb-4">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        {# {% include "security/_messages.html" %} #}
        <h1>{{ _fsdomain('Register') }}</h1>
        <form action="{{ url_for_security('register') }}" method="post" name="register_user_form">
          {{ register_user_form.hidden_tag() }}
          {{ render_form_errors(register_user_form) }}
          {{ render_field_with_errors(register_user_form.email, class_="form-control mb-2") }}
          {% if config["SECURITY_USERNAME_ENABLE"] %}{{ render_field_with_errors(register_user_form.username, class_="form-control mb-2") }}{% endif %}
          {{ render_field_with_errors(register_user_form.password, class_="form-control mb-2") }}
          {% if register_user_form.password_confirm %}
            {{ render_field_with_errors(register_user_form.password_confirm, class_="form-control mb-3") }}
          {% endif %}
          {{ render_field_errors(register_user_form.csrf_token) }}
          {{ render_field(register_user_form.submit, class_="btn btn-primary mb-2") }}
        </form>
    </div>
    <div class="col-sm-2">
    </div>
</div>
{% endblock content %}