mfo/admin/views.py
# mfo/admin/views.py

import flask
import flask_security
import mfo.admin.forms
from werkzeug.exceptions import Forbidden
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy import select, desc, asc
from sqlalchemy.sql import exists, func, text
from sqlalchemy.orm import selectinload, joinedload, aliased
from datetime import datetime
import pandas as pd
import os
import json
import io
from werkzeug.security import check_password_hash

from mfo.database.base import db
import mfo.admin.services.spreadsheet as spreadsheet
import mfo.admin.services.syllabus as syllabus
from mfo.database.models import School, Entry, Profile, FestivalClass, Repertoire, profiles_roles, entry_repertoire, participants_entries
from mfo.database.users import User, Role
import mfo.admin.services.admin_services as admin_services
import mfo.admin.forms as forms

bp = flask.Blueprint(
    'admin',
    __name__,
    static_folder='static',
    template_folder='templates',
    url_prefix='/admin',
    )


@bp.get ('/dashboard')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def dashboard():
    # need to add some data gathering here
    return flask.render_template('admin/dashboard.html')


@bp.get('/upload_syllabus')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def upload_syllabus_get():
    form = mfo.admin.forms.UploadSyllabusForm()
    return flask.render_template('admin/upload_syllabus.html', form=form)


@bp.post('/upload_syllabus')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def upload_syllabus_post():
    form = mfo.admin.forms.UploadSyllabusForm()
    if form.validate_on_submit():
        file = form.file.data
        if file.filename.endswith('.pdf'):
            syllabus.add_to_db(file)
            # I might make a different template for showing any issues or other ionformation related to a successful upload
            # For now, just redirect back to the Syllabus load page to show flask.flash messages, if they exist
            return flask.redirect(flask.url_for('admin.upload_registrations_get')) 
        else:
            flask.flash(
                f"Uploaded file is not a PDF file." +
                f"Please select the Syllabus PDF file",
                'danger'
                )
            return flask.redirect(flask.url_for('admin.upload_syllabus_get'))


@bp.get('/upload_registrations')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def upload_registrations_get():
    # # clear any flashes that may have been set
    # if '_flashes' in flask.session:
    #     flask.session['_flashes'].clear()
    # check if classes exist in the database
    stmt = select(FestivalClass)
    classes = db.session.execute(stmt).scalars().first()
    if not classes:
        flask.flash("No classes found in the database. Please upload a Syllabus file before uploading registration entries.", 'warning')
        return flask.redirect(flask.url_for('admin.upload_syllabus_get'))
    
    form = mfo.admin.forms.UploadRegistrationsForm()
    return flask.render_template('admin/upload_registrations.html', form=form)


@bp.post('/upload_registrations')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def upload_registrations_post():
    form = mfo.admin.forms.UploadRegistrationsForm()
    if form.validate_on_submit():
        file = form.file.data
        df, succeeded, message = spreadsheet.read_sheet(file)

        if not succeeded:
            flask.flash(message, 'danger')
            return flask.redirect(flask.url_for('admin.upload_registrations_get'))
        
        flask.flash(message, 'success')

        df = spreadsheet.names_to_df(df)
        issues, info = spreadsheet.gather_issues(df)
        

        if issues:
            flask.session['dataframe'] = df.to_json()
            flask.session['issues'] = json.dumps(issues)
            db.session.rollback()
        
        return flask.redirect(flask.url_for('admin.confirm_get'))

    
@bp.get('/confirm')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def confirm_get():
    form = mfo.admin.forms.ConfirmForm()
    issues_json = flask.session.get('issues', None)
    if issues_json:
        issues = json.loads(issues_json)
        flask.flash("Issues found. Review issues", 'warning')
        return flask.render_template('admin/list_issues.html', issues=issues, form=form)
    else:
        flask.flash("No issues found. Click Confirm to add spreadsheet data to MFO", 'success')
        issues = []
        return flask.render_template('admin/list_issues.html', issues=issues, form=form)
    # Note that the form in the confirm_form.html template included in the 
    # partials/list_issues.html template is not submitted with htmx; it is a normal POST request
    # so when the form is submitted, the confirm_post() function is called with a normal POST request
    # so the redirect reloads the entire page.


@bp.post('/confirm')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def confirm_post():
    form = mfo.admin.forms.ConfirmForm()
    if form.validate_on_submit():
        flask.session.pop('issues', None)
        if form.confirm.data:
            df = pd.read_json(flask.session.get('dataframe'))
            flask.session.pop('dataframe', None)
            issues, info = spreadsheet.gather_issues(df)
            spreadsheet.commit_to_db()
            flask.flash("Changes were committed to the database.", 'success')
            return flask.redirect(flask.url_for('admin.upload_registrations_get'))
        elif form.cancel.data:
            flask.flash("Upload cancelled by user. Database unchanged.", 'warning')
        else:
            flask.flash("Unexpected error! Changes were not committed to the database.", 'danger')
    
    return flask.redirect(flask.url_for('admin.upload_registrations_get'))


@bp.post('/generate_text_file')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def generate_text_file():
    file_name = flask.request.form.get('filename', 'issues.txt')

    output = io.BytesIO()
    
    issues_json = flask.session.get('issues', None)
    issues = json.loads(issues_json)

    for issue in issues:
        output.write((issue + "\n").encode('utf-8'))

    output.seek(0)

    return flask.send_file(output, mimetype='text/plain', as_attachment=True, download_name=file_name)


@bp.errorhandler(Forbidden)
def handle_forbidden(e):
    return flask.render_template('forbidden.html', role="Admin")


@bp.get('/report')
@flask_security.auth_required()
@flask_security.roles_required('Admin')
def profile_report_get():

    role = flask.request.args.get('role', None)
    report_name = flask.request.args.get('report_name', None)
    form = forms.ParticipantSortForm(role)

    sort_by = flask.request.args.getlist('sort_by')
    sort_order = flask.request.args.getlist('sort_order')
    page = int(flask.request.args.get('page', 1))
    per_page = int(flask.request.args.get('per_page', 10))
    hide_zero_entries = flask.request.args.get(
        'hide_zero_entries', 
        'false'
    ).lower() == 'true'

    if sort_by:
        sort_criteria = zip(sort_by, sort_order)
        for i, (sort_field, order_field) in enumerate(sort_criteria, start=1):
            setattr(getattr(form, f'sort{i}'), 'data', sort_field)
            setattr(getattr(form, f'order{i}'), 'data', order_field)
    else:
        if role == 'Group':
            form.sort1.data = 'group_name'
            sort_by = ['group_name']
        else:
            form.sort1.data = 'name'
            sort_by = ['name']

        form.order1.data = 'asc'
        sort_order = ['asc']

    form.page_rows.data = str(per_page) if per_page else '10'
    form.hide_zero_entries.data = hide_zero_entries
    # I don't do anything with hide_zero_entries yet, but I might in the future

    
    # Define aliases for Profile
    student_profile = aliased(Profile)
    teacher_profile = aliased(Profile)

    # Define subqueries for num_entries
    if role == 'Teacher':
        students_subquery = (
            select(
                teacher_profile.id.label("teacher_id"), 
                student_profile.id.label("student_id")
            ).outerjoin(
                student_profile, 
                teacher_profile.students
            ).group_by(
                teacher_profile.id, 
                student_profile.id
            )
        ).subquery()

        entries_subquery = (
            select(
                students_subquery.c.teacher_id.label("profile_id"),
                func.count(Entry.id).label('number_of_entries')
            ).outerjoin(
                student_profile, 
                student_profile.id == students_subquery.c.student_id
            ).outerjoin(
                Entry, 
                student_profile.participates_in_entries
            ).group_by(
                students_subquery.c.teacher_id
            )
        ).subquery()
        
    elif role == 'Accompanist':
        entries_subquery = (
            select(
                Profile.id.label("profile_id"), 
                func.count(Entry.id).label('number_of_entries')
            ).outerjoin(
                Entry, 
                Profile.accompanies_entries
            ).group_by(
                Profile.id
            )
        ).subquery()

    elif role == 'Participant' or role == 'Group':
        entries_subquery = (
            select(
                Profile.id.label("profile_id"),
                func.count(Entry.id).label("number_of_entries")
            ).outerjoin(
                Entry, 
                Profile.participates_in_entries
            ).group_by(
                Profile.id
            )
        ).subquery()

    else:
        raise ValueError(f"Invalid role found in profile_report_get() function: {role}")

    stmt = (
        select(
            Profile.id.label("id"),
            Profile.name.label("name"),

mfo/templates/base.html
<!-- mfo/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}MFO{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/styles.css" />
    {{ bootstrap.load_css() }}

    {% block additional_css %}{% endblock %}
    <script src="https://unpkg.com/htmx.org@2.0.0" integrity="sha384-wS5l5IKJBvK6sPTKa2WZ1js3d947pvWXbPJ1OmWfEuxLgeHcEbjUUA5i9V5ZkpCw" crossorigin="anonymous"></script>
    {% block additional_js %}{% endblock %}
</head>

<body>
    {% include "navbar.html" %}
    

    {% block content %}
    {% endblock %}

   
    {{ bootstrap.load_js() }}
</body>
</html>

mfo/templates/flash.html
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="alert-container pt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
</div>

mfo/templates/forbidden.html
<!-- mfo/templates/forbidden.html -->

{% extends "base.html" %}
{% block title %}Access forbidden{% endblock %}

{% block content %}
<div class="jumbotron text-center pt-4 pb-3 bg-light">
    <h1>Access forbidden</h1>
    <p>Sorry, you must be a {{role}} to access this page </p>
</div>
{% endblock %}

{% block additional_css %}{% endblock %}

mfo/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">MFO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapsed" aria-controls="navbarCollapsed" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapsed">
            <div class="navbar-nav me-auto text-light">
                {% if "Admin" in current_user.roles %}
                    {% include "navbar_admin.html" %}
                {% endif %}
            </div>
            <div class="navbar-nav ms-auto">
                {% if _fs_is_user_authenticated(current_user) %}
                    {% include "navbar_profile.html" %}
                {% else %}
                    <a class="nav-link" href="{{ url_for_security('register') }}">Register</a>
                    <a class="nav-link" href="{{ url_for('home.custom_login_get') }}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

mfo/templates/navbar_admin.html
<div class="dropdown">
    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Admin</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{{ url_for('admin.upload_syllabus_get') }}">Upload Syllabus</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.upload_registrations_get') }}">Upload Entries</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.delete_festival_data_get') }}">Delete Festival Data</a></li>
    </ul>
</div>
<div class="dropdown">
    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Reports</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{{ url_for('admin.classes_get') }}">Classes</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.repertoire_get') }}">Repertoire</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.profile_report_get', role='Teacher', report_name='Teachers') }}">Teachers</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.profile_report_get', role='Accompanist', report_name='Accompanists') }}">Accompanists</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.profile_report_get', role='Participant', report_name='Participants') }}">Individual Participants</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.profile_report_get', role='Group', report_name='Groups') }}">Group Participants</a></li>
    </ul>
</div>

mfo/templates/navbar_profile.html
<div class="dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Account</a>
    <div class="dropdown-menu">
        <div class="dropdown-item">
            <a class="nav-link" href="{{ url_for('account.index') }}">Profile</a>
        </div>
        <div class="dropdown-item">
            <a class="nav-link" href="{{ url_for_security('logout') }}">Logout</a>
        </div>
    </div>
</div>